<a href="https://colab.research.google.com/github/sweta8144/Internship-Goeduhub/blob/main/Corona_Virus_Infection_Probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Corona Virus Infection Probability using Machine Learning**

In [5]:
#importing the libraries

import pandas as pd
import numpy as np
import sklearn
from sklearn.metrics import mean_squared_error

In [6]:
#importing the csv file
data=pd.read_csv('/content/randomdata.csv')
data.head()

Fever   Age   BodyPain  ...  Travel   Cough  Probability
0     101   65          1  ...        1      1            1
1      98   59          0  ...        1      1            0
2     103   46          0  ...        0      0            0
3     104   83          0  ...        0      1            0
4      98   98          0  ...        0      0            0

[5 rows x 8 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fever               1999 non-null   int64
 1   Age                 1999 non-null   int64
 2    BodyPain           1999 non-null   int64
 3   DifficultyinBreath  1999 non-null   int64
 4   RunnyNose           1999 non-null   int64
 5   Travel              1999 non-null   int64
 6   Cough               1999 non-null   int64
 7   Probability         1999 non-null   int64
dtypes: int64(8)
memory usage: 125.1 KB


In [8]:
X=data.drop('Probability',axis=1)
print(X.head())
print('data in y')
Y=data['Probability']
Y.head()

   Fever   Age   BodyPain  DifficultyinBreath  RunnyNose  Travel   Cough
0     101   65          1                   0          0        1      1
1      98   59          0                   1          0        1      1
2     103   46          0                   1          1        0      0
3     104   83          0                   0          0        0      1
4      98   98          0                   0          1        0      0
data in y


0    1
1    0
2    0
3    0
4    0
Name: Probability, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

In [10]:
print(X_train.to_numpy())
Y_train.to_numpy()

X_test.to_numpy()
Y_test.to_numpy()

[[101  16   1 ...   0   0   1]
 [ 98  25   1 ...   0   0   0]
 [104  53   0 ...   1   1   0]
 ...
 [103  63   0 ...   0   1   1]
 [104  38   1 ...   1   1   1]
 [ 98 100   0 ...   1   1   1]]


array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [11]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
Y_train_pred=clf.fit(X_train,Y_train)

In [12]:
infection=clf.predict([[98,20,0,1,0,0,0]])

infection_probability= clf.predict_proba([[98,20,0,0,0,0,1]])

print(infection)

print(infection_probability)

[0]
[[0.47974979 0.52025021]]
