<a href="https://colab.research.google.com/github/sweta8144/Internship-Goeduhub/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Task 4**

**Name - SWETA LENKA**

**Reg no. - 11510**

**Q1. Import the numpy package under the name np and Print the numpy version and the configuration.**

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


**Q2. Create a null vector of size 10**

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]



**Q3. Create Simple 1-D array and check type and check data types in array**

In [4]:
a = np.array([10,20,30])
print(a)
print(a.dtype)

[10 20 30]
int64


**Q4. How to find number of dimensions, bytes per element and bytes of memory used?**

In [6]:
import sys
y = np.array([1,2,3,4,5,6])
print('Dimension of array is: ',y.size)
print('Bytes per element is: ',y.itemsize)
print('Bytes of memory used: ',y.nbytes)

Dimension of array is:  6
Bytes per element is:  8
Bytes of memory used:  48


**Q5. Create a null vector of size 10 but the fifth value which is 1**

In [7]:
x = np.zeros(10)
print(x)
print('Update fifth value to 1')
x[5]=1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]



Q6. Create a vector with values ranging from 10 to 49

In [8]:
z = np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]



Q7. Reverse a vector (first element becomes last)

In [9]:
m = np.arange(0,10)
print('Original vector: ',m)
m = m[::-1]
print('Reverse vector: ',m)

Original vector:  [0 1 2 3 4 5 6 7 8 9]
Reverse vector:  [9 8 7 6 5 4 3 2 1 0]



Q8. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
t = np.arange(0,9).reshape(3,3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



Q9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
n = [1,2,0,0,4,0]
print('Indices of non-zero elements are: ',np.nonzero(n))

Indices of non-zero elements are:  (array([0, 1, 4]),)


Q10. Create a 3x3 identity matrix

In [12]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



Q11. Create a 3x3x3 array with random values

In [13]:
x = np.random.random((3,3,3))
print(x)

[[[0.42592558 0.99135694 0.21211627]
  [0.47273145 0.41426733 0.79065908]
  [0.28976247 0.20771603 0.85301817]]

 [[0.29589852 0.48210426 0.41188028]
  [0.34967449 0.10771716 0.34322182]
  [0.17987294 0.36774183 0.16330259]]

 [[0.28957526 0.47512728 0.7889848 ]
  [0.61898656 0.78139851 0.39492889]
  [0.37769554 0.52866687 0.07530087]]]



Q12. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
x = np.random.random((10,10))
print(x)
print('Minimum value of the array is: ',x.min())
print('Maximum value of the array is: ',x.max())

[[0.7139564  0.01819641 0.02605994 0.11624972 0.6061734  0.25343529
  0.93546257 0.45963406 0.66523986 0.4816094 ]
 [0.48050375 0.14663518 0.15223369 0.52706728 0.76653846 0.53647953
  0.18315412 0.44742334 0.51680498 0.6471163 ]
 [0.90534961 0.60346658 0.13884921 0.20924708 0.69840802 0.82293158
  0.37414301 0.61502932 0.34766638 0.30907747]
 [0.06521934 0.46587146 0.72069645 0.90403225 0.69541518 0.68902388
  0.81620391 0.71273964 0.52042586 0.16801039]
 [0.86794575 0.66816865 0.27406947 0.93798783 0.18953343 0.55553133
  0.52884303 0.72562355 0.11301179 0.14506842]
 [0.59864076 0.03090145 0.37215623 0.85740076 0.1133404  0.44557674
  0.84329566 0.71399577 0.85794905 0.03758267]
 [0.8666582  0.72265131 0.4494002  0.1986315  0.51905436 0.07195201
  0.88257728 0.20812774 0.77388342 0.0839455 ]
 [0.52836861 0.51738605 0.68641673 0.95264657 0.46949438 0.22042373
  0.26885011 0.24470587 0.68581689 0.38450622]
 [0.77451149 0.99198044 0.94308228 0.14158028 0.99855736 0.07690328
  0.44407139


Q13. Create a random vector of size 30 and find the mean value

In [15]:
x = np.random.random((30))
print(x)
print('Mean value of the random vector is: ',x.mean())

[0.05944052 0.25465236 0.17602737 0.11398664 0.80684947 0.75111958
 0.69804012 0.59813283 0.08594211 0.71412021 0.71621287 0.49437647
 0.5435172  0.15991402 0.57813462 0.64411666 0.87115551 0.12704779
 0.32803399 0.65702503 0.54137206 0.33703571 0.30298753 0.11029656
 0.08714185 0.6853353  0.74130199 0.77172158 0.76744972 0.27441859]
Mean value of the random vector is:  0.466563542374451


Q14. Create a 2d array with 1 on the border and 0 inside

In [16]:
x = np.ones((7,7))
print('Original array: ')
print(x)
x[1:-1,1:-1]=0
print('2d array with 1 on the border and 0 inside: ')
print(x)

Original array: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
2d array with 1 on the border and 0 inside: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]



Q15. How to add a border (filled with 0's) around an existing array?

In [17]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]



Q16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [18]:
a = np.arange(1,15).reshape(2,7)
print(a)

#Get 13
print(a[1,5])

#Get first row only
print(a[0])

#Get 3rd column only
print(a[:,2])

#Get [2,4,6]
print([a[0,1],a[0,3],a[0,5]])

#Replace 13 by 20
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[2, 4, 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]



Q17. How to Convert a 1D array to a 2D array with 2 rows?

In [19]:
a = np.arange(10)
print('1D array:')
print(a)
a = a.reshape(2,5)
print('2D array with 2 rows:')
print(a)

1D array:
[0 1 2 3 4 5 6 7 8 9]
2D array with 2 rows:
[[0 1 2 3 4]
 [5 6 7 8 9]]



Q18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q19. Write a program to show how Numpy taking less memory compared to Python List?

In [21]:
import sys

l = range(100)
print('Size of each element of list in bytes: ',sys.getsizeof(l))
print('Size of the whole list in bytes: ',sys.getsizeof(l)*len(l))

a = np.arange(100)
print('Size of each element in the Numpy array in bytes: ',a.itemsize)
print('Size of the whole Numpy array in bites: ',a.itemsize*a.size)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  4800
Size of each element in the Numpy array in bytes:  8
Size of the whole Numpy array in bites:  800



Q20. Write a program to show how Numpy taking less time compared to Python List?

In [22]:
import sys
import time

size = 1000000
l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

#list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('Time taken by lists:')
print((time.time()-start)*1000)

#numpy array
start = time.time()
result1 = n1+n2
print('Time taken by numpy arrays')
print((time.time()-start)*1000)

Time taken by lists:
175.45008659362793
Time taken by numpy arrays
3.710508346557617
